### ISSUE TITLE
error in parmed

### ISSUE THREAD

**Issue by amrhamedp** [OleinikovasV/CrypticSWISH#1]
Setting LJ @%ca-@%ca pairwise interaction to have Rmin =          7.12719 and Epsilon =          0.00036

Traceback (most recent call last):
  File "modified.py", line 393, in <module>
    parm, lig_gmx_nonbond = add_interligand_repulsion(parm, lig_atomtypes, verbose=True)
  File "modified.py", line 266, in add_interligand_repulsion
    act_changeLJPair.execute()
  File "/software/anaconda2/envs/acemd/lib/python3.6/site-packages/parmed/tools/actions.py", line 602, in execute
    'First mask matches multiple atom types!')
parmed.tools.exceptions.ChangeLJPairError: First mask matches multiple atom types!

**Comment by OleinikovasV** [comment]
Are you using a mixture of ligands in the same simulation? It looks like you have different atomtype defined by the same name:
> 'First mask matches multiple atom types!'
Can you explain me what were you doing and what ligands are you using in your system, ideally including their topology files. Thanks!
